In [3]:
import torch

# Gradients with PyTorch

In [7]:
a = torch.ones((2,2),requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [8]:
a.requires_grad

True

In [13]:
#This allows you to create a tensor as usual then an additional line to allow it to accumulate gradients.
a = torch.ones((2,2,))
a.requires_grad_()
a.requires_grad


True

In [14]:
#If you do not do either of the methods above, you'll realize you will get False for checking for gradients.
no_gradient = torch.ones((2,2))

In [15]:
no_gradient.requires_grad

False

# Tensor with gradients addition operation

In [17]:
b = torch.ones((1,1),requires_grad=True)
print(a+b)
print(torch.add(a,b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


# Tensor with gradients multiplication operation

In [18]:
print(a*b)
print(torch.mul(a,b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


# Manually and Automatically Calculating Gradients
What exactly is requires_grad? - Allows calculation of gradients w.r.t. the tensor that all allows gradients accumulation
y_i = 5(x_i+1)^2

In [20]:
#Create tensor of size 2x1 filled with 1's that requires gradient
x = torch.ones(2,requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

In [21]:
#Simple linear equation with x tensor created
#y_i\bigr\rvert_{x_i=1} = 5(1 + 1)^2 = 5(2)^2 = 5(4) = 20
y = 5*(x+1)**2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

In [22]:
#Simple equation with y tensor
#Backward should be called only on a scalar (i.e. 1-element tensor) or with gradient w.r.t. the variable
#Let's reduce y to a scalar then...
#o = \frac{1}{2}\sum_i y_i
#As you can see above, we've a tensor filled with 20's, so average them would return 20
o = (1/2) *torch.sum(y)
o

tensor(20., grad_fn=<MulBackward0>)

# Calculating first derivative
Recap y equation: y_i = 5(x_i+1)^2
Recap o equation: o = \frac{1}{2}\sum_i y_i
Substitute y into o equation: o = \frac{1}{2} \sum_i 5(x_i+1)^2
\frac{\partial o}{\partial x_i} = \frac{1}{2}[10(x_i+1)]
\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{1}{2}[10(1 + 1)] = \frac{10}{2}(2) = 10

In [24]:
o.backward()

In [25]:
x.grad

tensor([10., 10.])

# If x requires gradient and you create new objects with it, you get all gradients

In [26]:
print(x.requires_grad)
print(y.requires_grad)
print(o.requires_grad)

True
True
True
