In [4]:
import pandas as pd
import numpy as np
import torch

# matrix and tensor brief intro 

In [10]:
arr = [[1,2,3],[4,5,6]]#create a multi dimesional array using standard python list

In [11]:
np.array(arr) #use numpy to make a multi dimensional array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
torch.tensor(arr)#turn multi dimensional array to tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

# matrices with default values

In [14]:
np.ones((2,2)) # a 2x2 matrix with all ones 

array([[1., 1.],
       [1., 1.]])

In [16]:
torch.ones((2,2)) # a 2x2 tensor of ones

tensor([[1., 1.],
        [1., 1.]])

In [17]:
np.random.rand(2,2) # a random 2x2 matrix with random ints

array([[0.09450773, 0.68014169],
       [0.70725368, 0.78404955]])

In [20]:
torch.rand(2,2) # a random 2x2 tensor

tensor([[0.2191, 0.1221],
        [0.6532, 0.7493]])

# Seeds
We need seeds to enable reproduction of experimental results. 
This becomes critical later on where you can easily let people reproduce your code's output exactly as you've produced.

# Create seed to enable fixed numbers for random number generation

In [21]:
np.random.seed(0) # a seed of 0
np.random.rand(2,2)


array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

# Create a numpy array without seed

Notice how you get different numbers compared to the first 2 tries?

In [22]:
np.random.rand(2,2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

# Repeat numpy array generation without seed

You get the point now, you get a totally different set of numbers.

In [25]:
np.random.rand(2,2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

# Tensor with seed

In [27]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [28]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

# seedless Tensor 

In [29]:
torch.rand(2,2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [30]:
torch.rand(2,2)

tensor([[0.4556, 0.6323],
        [0.3489, 0.4017]])

# Seed for GPU is different for now...

# Fix a seed for GPU tensors

When you conduct deep learning experiments, typically you want to use GPUs to accelerate your computations 
and fixing seed for tensors on GPUs is different from CPUs as we have done above.

# NumPy to Torch

In [35]:
np_array = np.ones((2,2))
print(np_array)
print(type(np_array))

[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


In [36]:
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)
print(type(torch_tensor))

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
<class 'torch.Tensor'>


# Create PyTorch tensor from a different numpy datatype

You may get an error running this code because PyTorch tensor don't support all datatype.

In [40]:
np_array_new = np.ones((2,2),dtype = np.int8)
torch_tensor = torch.from_numpy(np_array_new)
print(torch_tensor)


tensor([[1, 1],
        [1, 1]], dtype=torch.int8)


In [41]:
np_array_new2 = np.ones((2,2),dtype=np.int64)
torch_tensor2 = torch.from_numpy(np_array_new)
print(torch_tensor)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)


# Torch to NumPy

In [43]:
torch_tensor = torch.ones(2,2)
print(type(torch_tensor))
print(torch_tensor)

<class 'torch.Tensor'>
tensor([[1., 1.],
        [1., 1.]])


In [45]:
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

# Tensors on CPU vs GPU

In [52]:
 # by default its on the cpu
tensor_cpu = torch.ones(2,2) # by default its on the cpu
print(tensor_cpu)

tensor([[1., 1.],
        [1., 1.]])


In [53]:
#cpu to GPU
device = torch.device('cuda:0' if torch.cuda.is_available() else "cpu" )
tensor_cpu.to(device)

tensor([[1., 1.],
        [1., 1.]])

In [54]:
#GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

# Tensor Operations

In [56]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [57]:
print(a.size())

torch.Size([2, 2])


In [59]:
#resize tensor
a.view(4)

tensor([1., 1., 1., 1.])

In [60]:
a.view(4).size()

torch.Size([4])

# Element-wise Addition

In [61]:
a = torch.ones(2,2)

In [63]:
b = torch.ones(2,2)

In [64]:
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [65]:
c = torch.add(a,b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [69]:
#In-place element-wise addition
print( 'old tensor c')
print(c)
print('-'*60)
c.add_(a)
print('new tensor c')
print(c)

old tensor c
tensor([[2., 2.],
        [2., 2.]])
------------------------------------------------------------
new tensor c
tensor([[3., 3.],
        [3., 3.]])


In [70]:
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [71]:
print(b)

tensor([[1., 1.],
        [1., 1.]])


# Element-wise subtraction

In [72]:
#method 1
a - b

tensor([[0., 0.],
        [0., 0.]])

In [73]:
print(a.sub(b))

tensor([[0., 0.],
        [0., 0.]])


In [74]:
#inplace notice the difference is the "-"
print(a.sub_(b))

tensor([[0., 0.],
        [0., 0.]])


In [75]:
print(a)

tensor([[0., 0.],
        [0., 0.]])


In [76]:
print(b)

tensor([[1., 1.],
        [1., 1.]])


# Element-Wise Multiplication

In [77]:
a = torch.ones(2,2)
b = torch.zeros(2,2)

In [78]:
a * b

tensor([[0., 0.],
        [0., 0.]])

In [80]:
print(a.mul(b))

tensor([[0., 0.],
        [0., 0.]])


In [81]:
#in place
print(a.mul_(b))

tensor([[0., 0.],
        [0., 0.]])


In [82]:
print(a)

tensor([[0., 0.],
        [0., 0.]])


# Element-Wise Division

In [83]:
a = torch.ones(2,2)
b = torch.zeros(2,2)

In [84]:
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [85]:
print(b)

tensor([[0., 0.],
        [0., 0.]])


In [89]:
b/a

tensor([[0., 0.],
        [0., 0.]])

In [90]:
b//a

tensor([[0., 0.],
        [0., 0.]])

In [91]:
print(b.div(a))

tensor([[0., 0.],
        [0., 0.]])


In [92]:
#inplace
print(b.div_(a))

tensor([[0., 0.],
        [0., 0.]])


In [93]:
print(b)

tensor([[0., 0.],
        [0., 0.]])


In [94]:
print(a)

tensor([[1., 1.],
        [1., 1.]])


# Tensor Mean

In [97]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [99]:
#we use dim = 0 because there is no dimensionss to this tensor this is a size 10 if it was 10x1 then use dim=1 and etc...
a_mean = a.mean(dim=0)
print(a_mean)

tensor(5.5000)


In [100]:
a = torch.Tensor([[1,2,3,4,5,6,7,8,9,10]])
a.size()

torch.Size([1, 10])

In [101]:
a_mean = a.mean(dim=1)
print(a_mean)

tensor([5.5000])


In [104]:
a = torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
a.size()

torch.Size([2, 10])

In [106]:
a_mean = a.mean(dim=1)
print(a_mean)

tensor([5.5000, 5.5000])


# Tensor Standard Deviation

In [107]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [108]:
a.std(dim=0)

tensor(3.0277)